// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t_y_route_geometry_pbf.proto

package cn.platalk.core.pbf.route;

public final class TYRouteGeometryPbf {
  private TYRouteGeometryPbf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TYRouteCoordPbfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.platalk.core.pbf.route.TYRouteCoordPbf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required double x = 1;</code>
     */
    double getX();

    /**
     * <code>required double y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required double y = 2;</code>
     */
    double getY();
  }
  /**
   * Protobuf type {@code cn.platalk.core.pbf.route.TYRouteCoordPbf}
   */
  public  static final class TYRouteCoordPbf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.platalk.core.pbf.route.TYRouteCoordPbf)
      TYRouteCoordPbfOrBuilder {
    // Use TYRouteCoordPbf.newBuilder() to construct.
    private TYRouteCoordPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TYRouteCoordPbf() {
      x_ = 0D;
      y_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TYRouteCoordPbf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.class, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>required double x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double x = 1;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>required double y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double y = 2;</code>
     */
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf)) {
        return super.equals(obj);
      }
      cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf other = (cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf) obj;

      boolean result = true;
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getX())
            == java.lang.Double.doubleToLongBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getY())
            == java.lang.Double.doubleToLongBits(
                other.getY()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getX()));
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getY()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.platalk.core.pbf.route.TYRouteCoordPbf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.platalk.core.pbf.route.TYRouteCoordPbf)
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.class, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder.class);
      }

      // Construct using cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor;
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getDefaultInstanceForType() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.getDefaultInstance();
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf build() {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf buildPartial() {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf result = new cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf) {
          return mergeFrom((cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf other) {
        if (other == cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>required double x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double x = 1;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>required double x = 1;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>required double y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double y = 2;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>required double y = 2;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.platalk.core.pbf.route.TYRouteCoordPbf)
    }

    // @@protoc_insertion_point(class_scope:cn.platalk.core.pbf.route.TYRouteCoordPbf)
    private static final cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf();
    }

    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TYRouteCoordPbf>
        PARSER = new com.google.protobuf.AbstractParser<TYRouteCoordPbf>() {
      public TYRouteCoordPbf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TYRouteCoordPbf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TYRouteCoordPbf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TYRouteCoordPbf> getParserForType() {
      return PARSER;
    }

    public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TYRouteLineStringPbfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.platalk.core.pbf.route.TYRouteLineStringPbf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> 
        getCoordsList();
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getCoords(int index);
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    int getCoordsCount();
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    java.util.List<? extends cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder> 
        getCoordsOrBuilderList();
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder getCoordsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.platalk.core.pbf.route.TYRouteLineStringPbf}
   */
  public  static final class TYRouteLineStringPbf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.platalk.core.pbf.route.TYRouteLineStringPbf)
      TYRouteLineStringPbfOrBuilder {
    // Use TYRouteLineStringPbf.newBuilder() to construct.
    private TYRouteLineStringPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TYRouteLineStringPbf() {
      coords_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TYRouteLineStringPbf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                coords_ = new java.util.ArrayList<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf>();
                mutable_bitField0_ |= 0x00000001;
              }
              coords_.add(
                  input.readMessage(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          coords_ = java.util.Collections.unmodifiableList(coords_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.class, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.Builder.class);
    }

    public static final int COORDS_FIELD_NUMBER = 1;
    private java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> coords_;
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    public java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> getCoordsList() {
      return coords_;
    }
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    public java.util.List<? extends cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder> 
        getCoordsOrBuilderList() {
      return coords_;
    }
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    public int getCoordsCount() {
      return coords_.size();
    }
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getCoords(int index) {
      return coords_.get(index);
    }
    /**
     * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
     */
    public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder getCoordsOrBuilder(
        int index) {
      return coords_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCoordsCount(); i++) {
        if (!getCoords(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < coords_.size(); i++) {
        output.writeMessage(1, coords_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coords_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, coords_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf)) {
        return super.equals(obj);
      }
      cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf other = (cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf) obj;

      boolean result = true;
      result = result && getCoordsList()
          .equals(other.getCoordsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCoordsCount() > 0) {
        hash = (37 * hash) + COORDS_FIELD_NUMBER;
        hash = (53 * hash) + getCoordsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.platalk.core.pbf.route.TYRouteLineStringPbf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.platalk.core.pbf.route.TYRouteLineStringPbf)
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.class, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.Builder.class);
      }

      // Construct using cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCoordsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (coordsBuilder_ == null) {
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coordsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor;
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf getDefaultInstanceForType() {
        return cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.getDefaultInstance();
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf build() {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf buildPartial() {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf result = new cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf(this);
        int from_bitField0_ = bitField0_;
        if (coordsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            coords_ = java.util.Collections.unmodifiableList(coords_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coords_ = coords_;
        } else {
          result.coords_ = coordsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf) {
          return mergeFrom((cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf other) {
        if (other == cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf.getDefaultInstance()) return this;
        if (coordsBuilder_ == null) {
          if (!other.coords_.isEmpty()) {
            if (coords_.isEmpty()) {
              coords_ = other.coords_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoordsIsMutable();
              coords_.addAll(other.coords_);
            }
            onChanged();
          }
        } else {
          if (!other.coords_.isEmpty()) {
            if (coordsBuilder_.isEmpty()) {
              coordsBuilder_.dispose();
              coordsBuilder_ = null;
              coords_ = other.coords_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coordsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCoordsFieldBuilder() : null;
            } else {
              coordsBuilder_.addAllMessages(other.coords_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCoordsCount(); i++) {
          if (!getCoords(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> coords_ =
        java.util.Collections.emptyList();
      private void ensureCoordsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          coords_ = new java.util.ArrayList<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf>(coords_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder> coordsBuilder_;

      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> getCoordsList() {
        if (coordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coords_);
        } else {
          return coordsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public int getCoordsCount() {
        if (coordsBuilder_ == null) {
          return coords_.size();
        } else {
          return coordsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf getCoords(int index) {
        if (coordsBuilder_ == null) {
          return coords_.get(index);
        } else {
          return coordsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder setCoords(
          int index, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf value) {
        if (coordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordsIsMutable();
          coords_.set(index, value);
          onChanged();
        } else {
          coordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder setCoords(
          int index, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder builderForValue) {
        if (coordsBuilder_ == null) {
          ensureCoordsIsMutable();
          coords_.set(index, builderForValue.build());
          onChanged();
        } else {
          coordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder addCoords(cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf value) {
        if (coordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordsIsMutable();
          coords_.add(value);
          onChanged();
        } else {
          coordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder addCoords(
          int index, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf value) {
        if (coordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordsIsMutable();
          coords_.add(index, value);
          onChanged();
        } else {
          coordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder addCoords(
          cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder builderForValue) {
        if (coordsBuilder_ == null) {
          ensureCoordsIsMutable();
          coords_.add(builderForValue.build());
          onChanged();
        } else {
          coordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder addCoords(
          int index, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder builderForValue) {
        if (coordsBuilder_ == null) {
          ensureCoordsIsMutable();
          coords_.add(index, builderForValue.build());
          onChanged();
        } else {
          coordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder addAllCoords(
          java.lang.Iterable<? extends cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf> values) {
        if (coordsBuilder_ == null) {
          ensureCoordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coords_);
          onChanged();
        } else {
          coordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder clearCoords() {
        if (coordsBuilder_ == null) {
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public Builder removeCoords(int index) {
        if (coordsBuilder_ == null) {
          ensureCoordsIsMutable();
          coords_.remove(index);
          onChanged();
        } else {
          coordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder getCoordsBuilder(
          int index) {
        return getCoordsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder getCoordsOrBuilder(
          int index) {
        if (coordsBuilder_ == null) {
          return coords_.get(index);  } else {
          return coordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public java.util.List<? extends cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder> 
           getCoordsOrBuilderList() {
        if (coordsBuilder_ != null) {
          return coordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coords_);
        }
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder addCoordsBuilder() {
        return getCoordsFieldBuilder().addBuilder(
            cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder addCoordsBuilder(
          int index) {
        return getCoordsFieldBuilder().addBuilder(
            index, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.platalk.core.pbf.route.TYRouteCoordPbf coords = 1;</code>
       */
      public java.util.List<cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder> 
           getCoordsBuilderList() {
        return getCoordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder> 
          getCoordsFieldBuilder() {
        if (coordsBuilder_ == null) {
          coordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbf.Builder, cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteCoordPbfOrBuilder>(
                  coords_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          coords_ = null;
        }
        return coordsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.platalk.core.pbf.route.TYRouteLineStringPbf)
    }

    // @@protoc_insertion_point(class_scope:cn.platalk.core.pbf.route.TYRouteLineStringPbf)
    private static final cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf();
    }

    public static cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TYRouteLineStringPbf>
        PARSER = new com.google.protobuf.AbstractParser<TYRouteLineStringPbf>() {
      public TYRouteLineStringPbf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TYRouteLineStringPbf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TYRouteLineStringPbf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TYRouteLineStringPbf> getParserForType() {
      return PARSER;
    }

    public cn.platalk.core.pbf.route.TYRouteGeometryPbf.TYRouteLineStringPbf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034t_y_route_geometry_pbf.proto\022\031cn.plata" +
      "lk.core.pbf.route\"\'\n\017TYRouteCoordPbf\022\t\n\001" +
      "x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\"R\n\024TYRouteLineStringP" +
      "bf\022:\n\006coords\030\001 \003(\0132*.cn.platalk.core.pbf" +
      ".route.TYRouteCoordPbf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_platalk_core_pbf_route_TYRouteCoordPbf_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_platalk_core_pbf_route_TYRouteLineStringPbf_descriptor,
        new java.lang.String[] { "Coords", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
