// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t_y_poi_pbf.proto

package innerpeacer.mapdata.pbf;

@SuppressWarnings({"unused","unchecked"})
public final class TYPoiPbf {
  private TYPoiPbf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PoiPbfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:innerpeacer.mapdata.pbf.PoiPbf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    boolean hasPoiID();
    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    java.lang.String getPoiID();
    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    com.google.protobuf.ByteString
        getPoiIDBytes();

    /**
     * <pre>
     *required string buildingID = 3;
     *required string floorID = 4;
     * </pre>
     *
     * <code>required int32 floor = 5;</code>
     */
    boolean hasFloor();
    /**
     * <pre>
     *required string buildingID = 3;
     *required string floorID = 4;
     * </pre>
     *
     * <code>required int32 floor = 5;</code>
     */
    int getFloor();

    /**
     * <pre>
     *required string floorName = 6;
     * </pre>
     *
     * <code>required int32 layer = 7;</code>
     */
    boolean hasLayer();
    /**
     * <pre>
     *required string floorName = 6;
     * </pre>
     *
     * <code>required int32 layer = 7;</code>
     */
    int getLayer();

    /**
     * <code>optional string name = 8;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 8;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 8;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    boolean hasCategoryID();
    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    java.lang.String getCategoryID();
    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    com.google.protobuf.ByteString
        getCategoryIDBytes();

    /**
     * <code>optional double labelX = 11;</code>
     */
    boolean hasLabelX();
    /**
     * <code>optional double labelX = 11;</code>
     */
    double getLabelX();

    /**
     * <code>optional double labelY = 12;</code>
     */
    boolean hasLabelY();
    /**
     * <code>optional double labelY = 12;</code>
     */
    double getLabelY();
  }
  /**
   * Protobuf type {@code innerpeacer.mapdata.pbf.PoiPbf}
   */
  public  static final class PoiPbf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:innerpeacer.mapdata.pbf.PoiPbf)
      PoiPbfOrBuilder {
    // Use PoiPbf.newBuilder() to construct.
    private PoiPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PoiPbf() {
      poiID_ = "";
      floor_ = 0;
      layer_ = 0;
      name_ = "";
      categoryID_ = "";
      labelX_ = 0D;
      labelY_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PoiPbf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              poiID_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              floor_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000004;
              layer_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              name_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              categoryID_ = bs;
              break;
            }
            case 89: {
              bitField0_ |= 0x00000020;
              labelX_ = input.readDouble();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000040;
              labelY_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiPbf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.class, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder.class);
    }

    private int bitField0_;
    public static final int POIID_FIELD_NUMBER = 2;
    private volatile java.lang.Object poiID_;
    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    public boolean hasPoiID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    public java.lang.String getPoiID() {
      java.lang.Object ref = poiID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          poiID_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *required string geoID = 1;
     * </pre>
     *
     * <code>required string poiID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPoiIDBytes() {
      java.lang.Object ref = poiID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poiID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOOR_FIELD_NUMBER = 5;
    private int floor_;
    /**
     * <pre>
     *required string buildingID = 3;
     *required string floorID = 4;
     * </pre>
     *
     * <code>required int32 floor = 5;</code>
     */
    public boolean hasFloor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *required string buildingID = 3;
     *required string floorID = 4;
     * </pre>
     *
     * <code>required int32 floor = 5;</code>
     */
    public int getFloor() {
      return floor_;
    }

    public static final int LAYER_FIELD_NUMBER = 7;
    private int layer_;
    /**
     * <pre>
     *required string floorName = 6;
     * </pre>
     *
     * <code>required int32 layer = 7;</code>
     */
    public boolean hasLayer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *required string floorName = 6;
     * </pre>
     *
     * <code>required int32 layer = 7;</code>
     */
    public int getLayer() {
      return layer_;
    }

    public static final int NAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 8;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string name = 8;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORYID_FIELD_NUMBER = 9;
    private volatile java.lang.Object categoryID_;
    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    public boolean hasCategoryID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    public java.lang.String getCategoryID() {
      java.lang.Object ref = categoryID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          categoryID_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *optional uint32 symbolID = 10;
     * </pre>
     *
     * <code>optional string categoryID = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryIDBytes() {
      java.lang.Object ref = categoryID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABELX_FIELD_NUMBER = 11;
    private double labelX_;
    /**
     * <code>optional double labelX = 11;</code>
     */
    public boolean hasLabelX() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double labelX = 11;</code>
     */
    public double getLabelX() {
      return labelX_;
    }

    public static final int LABELY_FIELD_NUMBER = 12;
    private double labelY_;
    /**
     * <code>optional double labelY = 12;</code>
     */
    public boolean hasLabelY() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double labelY = 12;</code>
     */
    public double getLabelY() {
      return labelY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPoiID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFloor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, poiID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(5, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(7, layer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, name_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, categoryID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(11, labelX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(12, labelY_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, poiID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, layer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, name_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, categoryID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, labelX_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, labelY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf)) {
        return super.equals(obj);
      }
      innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf other = (innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf) obj;

      boolean result = true;
      result = result && (hasPoiID() == other.hasPoiID());
      if (hasPoiID()) {
        result = result && getPoiID()
            .equals(other.getPoiID());
      }
      result = result && (hasFloor() == other.hasFloor());
      if (hasFloor()) {
        result = result && (getFloor()
            == other.getFloor());
      }
      result = result && (hasLayer() == other.hasLayer());
      if (hasLayer()) {
        result = result && (getLayer()
            == other.getLayer());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasCategoryID() == other.hasCategoryID());
      if (hasCategoryID()) {
        result = result && getCategoryID()
            .equals(other.getCategoryID());
      }
      result = result && (hasLabelX() == other.hasLabelX());
      if (hasLabelX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLabelX())
            == java.lang.Double.doubleToLongBits(
                other.getLabelX()));
      }
      result = result && (hasLabelY() == other.hasLabelY());
      if (hasLabelY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLabelY())
            == java.lang.Double.doubleToLongBits(
                other.getLabelY()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPoiID()) {
        hash = (37 * hash) + POIID_FIELD_NUMBER;
        hash = (53 * hash) + getPoiID().hashCode();
      }
      if (hasFloor()) {
        hash = (37 * hash) + FLOOR_FIELD_NUMBER;
        hash = (53 * hash) + getFloor();
      }
      if (hasLayer()) {
        hash = (37 * hash) + LAYER_FIELD_NUMBER;
        hash = (53 * hash) + getLayer();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasCategoryID()) {
        hash = (37 * hash) + CATEGORYID_FIELD_NUMBER;
        hash = (53 * hash) + getCategoryID().hashCode();
      }
      if (hasLabelX()) {
        hash = (37 * hash) + LABELX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLabelX()));
      }
      if (hasLabelY()) {
        hash = (37 * hash) + LABELY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLabelY()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code innerpeacer.mapdata.pbf.PoiPbf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:innerpeacer.mapdata.pbf.PoiPbf)
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiPbf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.class, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder.class);
      }

      // Construct using innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        poiID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        floor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        layer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        categoryID_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        labelX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        labelY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor;
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getDefaultInstanceForType() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.getDefaultInstance();
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf build() {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf buildPartial() {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf result = new innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.poiID_ = poiID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.floor_ = floor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.layer_ = layer_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.categoryID_ = categoryID_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.labelX_ = labelX_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.labelY_ = labelY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf) {
          return mergeFrom((innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf other) {
        if (other == innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.getDefaultInstance()) return this;
        if (other.hasPoiID()) {
          bitField0_ |= 0x00000001;
          poiID_ = other.poiID_;
          onChanged();
        }
        if (other.hasFloor()) {
          setFloor(other.getFloor());
        }
        if (other.hasLayer()) {
          setLayer(other.getLayer());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCategoryID()) {
          bitField0_ |= 0x00000010;
          categoryID_ = other.categoryID_;
          onChanged();
        }
        if (other.hasLabelX()) {
          setLabelX(other.getLabelX());
        }
        if (other.hasLabelY()) {
          setLabelY(other.getLabelY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPoiID()) {
          return false;
        }
        if (!hasFloor()) {
          return false;
        }
        if (!hasLayer()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object poiID_ = "";
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public boolean hasPoiID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public java.lang.String getPoiID() {
        java.lang.Object ref = poiID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            poiID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPoiIDBytes() {
        java.lang.Object ref = poiID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          poiID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public Builder setPoiID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        poiID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public Builder clearPoiID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        poiID_ = getDefaultInstance().getPoiID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required string geoID = 1;
       * </pre>
       *
       * <code>required string poiID = 2;</code>
       */
      public Builder setPoiIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        poiID_ = value;
        onChanged();
        return this;
      }

      private int floor_ ;
      /**
       * <pre>
       *required string buildingID = 3;
       *required string floorID = 4;
       * </pre>
       *
       * <code>required int32 floor = 5;</code>
       */
      public boolean hasFloor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *required string buildingID = 3;
       *required string floorID = 4;
       * </pre>
       *
       * <code>required int32 floor = 5;</code>
       */
      public int getFloor() {
        return floor_;
      }
      /**
       * <pre>
       *required string buildingID = 3;
       *required string floorID = 4;
       * </pre>
       *
       * <code>required int32 floor = 5;</code>
       */
      public Builder setFloor(int value) {
        bitField0_ |= 0x00000002;
        floor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required string buildingID = 3;
       *required string floorID = 4;
       * </pre>
       *
       * <code>required int32 floor = 5;</code>
       */
      public Builder clearFloor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        floor_ = 0;
        onChanged();
        return this;
      }

      private int layer_ ;
      /**
       * <pre>
       *required string floorName = 6;
       * </pre>
       *
       * <code>required int32 layer = 7;</code>
       */
      public boolean hasLayer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *required string floorName = 6;
       * </pre>
       *
       * <code>required int32 layer = 7;</code>
       */
      public int getLayer() {
        return layer_;
      }
      /**
       * <pre>
       *required string floorName = 6;
       * </pre>
       *
       * <code>required int32 layer = 7;</code>
       */
      public Builder setLayer(int value) {
        bitField0_ |= 0x00000004;
        layer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required string floorName = 6;
       * </pre>
       *
       * <code>required int32 layer = 7;</code>
       */
      public Builder clearLayer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        layer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 8;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string name = 8;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object categoryID_ = "";
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public boolean hasCategoryID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public java.lang.String getCategoryID() {
        java.lang.Object ref = categoryID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            categoryID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryIDBytes() {
        java.lang.Object ref = categoryID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          categoryID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public Builder setCategoryID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        categoryID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public Builder clearCategoryID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        categoryID_ = getDefaultInstance().getCategoryID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional uint32 symbolID = 10;
       * </pre>
       *
       * <code>optional string categoryID = 9;</code>
       */
      public Builder setCategoryIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        categoryID_ = value;
        onChanged();
        return this;
      }

      private double labelX_ ;
      /**
       * <code>optional double labelX = 11;</code>
       */
      public boolean hasLabelX() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double labelX = 11;</code>
       */
      public double getLabelX() {
        return labelX_;
      }
      /**
       * <code>optional double labelX = 11;</code>
       */
      public Builder setLabelX(double value) {
        bitField0_ |= 0x00000020;
        labelX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double labelX = 11;</code>
       */
      public Builder clearLabelX() {
        bitField0_ = (bitField0_ & ~0x00000020);
        labelX_ = 0D;
        onChanged();
        return this;
      }

      private double labelY_ ;
      /**
       * <code>optional double labelY = 12;</code>
       */
      public boolean hasLabelY() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double labelY = 12;</code>
       */
      public double getLabelY() {
        return labelY_;
      }
      /**
       * <code>optional double labelY = 12;</code>
       */
      public Builder setLabelY(double value) {
        bitField0_ |= 0x00000040;
        labelY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double labelY = 12;</code>
       */
      public Builder clearLabelY() {
        bitField0_ = (bitField0_ & ~0x00000040);
        labelY_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:innerpeacer.mapdata.pbf.PoiPbf)
    }

    // @@protoc_insertion_point(class_scope:innerpeacer.mapdata.pbf.PoiPbf)
    private static final innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf();
    }

    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PoiPbf>
        PARSER = new com.google.protobuf.AbstractParser<PoiPbf>() {
      public PoiPbf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PoiPbf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PoiPbf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PoiPbf> getParserForType() {
      return PARSER;
    }

    public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PoiCollectionPbfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:innerpeacer.mapdata.pbf.PoiCollectionPbf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> 
        getPoisList();
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getPois(int index);
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    int getPoisCount();
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    java.util.List<? extends innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder> 
        getPoisOrBuilderList();
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder getPoisOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code innerpeacer.mapdata.pbf.PoiCollectionPbf}
   */
  public  static final class PoiCollectionPbf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:innerpeacer.mapdata.pbf.PoiCollectionPbf)
      PoiCollectionPbfOrBuilder {
    // Use PoiCollectionPbf.newBuilder() to construct.
    private PoiCollectionPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PoiCollectionPbf() {
      pois_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PoiCollectionPbf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pois_ = new java.util.ArrayList<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf>();
                mutable_bitField0_ |= 0x00000001;
              }
              pois_.add(
                  input.readMessage(innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pois_ = java.util.Collections.unmodifiableList(pois_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.class, innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.Builder.class);
    }

    public static final int POIS_FIELD_NUMBER = 1;
    private java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> pois_;
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    public java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> getPoisList() {
      return pois_;
    }
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    public java.util.List<? extends innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder> 
        getPoisOrBuilderList() {
      return pois_;
    }
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    public int getPoisCount() {
      return pois_.size();
    }
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getPois(int index) {
      return pois_.get(index);
    }
    /**
     * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
     */
    public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder getPoisOrBuilder(
        int index) {
      return pois_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPoisCount(); i++) {
        if (!getPois(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pois_.size(); i++) {
        output.writeMessage(1, pois_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pois_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pois_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf)) {
        return super.equals(obj);
      }
      innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf other = (innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf) obj;

      boolean result = true;
      result = result && getPoisList()
          .equals(other.getPoisList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPoisCount() > 0) {
        hash = (37 * hash) + POIS_FIELD_NUMBER;
        hash = (53 * hash) + getPoisList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code innerpeacer.mapdata.pbf.PoiCollectionPbf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:innerpeacer.mapdata.pbf.PoiCollectionPbf)
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.class, innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.Builder.class);
      }

      // Construct using innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPoisFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (poisBuilder_ == null) {
          pois_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          poisBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor;
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf getDefaultInstanceForType() {
        return innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.getDefaultInstance();
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf build() {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf buildPartial() {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf result = new innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf(this);
        int from_bitField0_ = bitField0_;
        if (poisBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pois_ = java.util.Collections.unmodifiableList(pois_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pois_ = pois_;
        } else {
          result.pois_ = poisBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf) {
          return mergeFrom((innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf other) {
        if (other == innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf.getDefaultInstance()) return this;
        if (poisBuilder_ == null) {
          if (!other.pois_.isEmpty()) {
            if (pois_.isEmpty()) {
              pois_ = other.pois_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePoisIsMutable();
              pois_.addAll(other.pois_);
            }
            onChanged();
          }
        } else {
          if (!other.pois_.isEmpty()) {
            if (poisBuilder_.isEmpty()) {
              poisBuilder_.dispose();
              poisBuilder_ = null;
              pois_ = other.pois_;
              bitField0_ = (bitField0_ & ~0x00000001);
              poisBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPoisFieldBuilder() : null;
            } else {
              poisBuilder_.addAllMessages(other.pois_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPoisCount(); i++) {
          if (!getPois(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> pois_ =
        java.util.Collections.emptyList();
      private void ensurePoisIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pois_ = new java.util.ArrayList<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf>(pois_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder> poisBuilder_;

      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> getPoisList() {
        if (poisBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pois_);
        } else {
          return poisBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public int getPoisCount() {
        if (poisBuilder_ == null) {
          return pois_.size();
        } else {
          return poisBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf getPois(int index) {
        if (poisBuilder_ == null) {
          return pois_.get(index);
        } else {
          return poisBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder setPois(
          int index, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf value) {
        if (poisBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoisIsMutable();
          pois_.set(index, value);
          onChanged();
        } else {
          poisBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder setPois(
          int index, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder builderForValue) {
        if (poisBuilder_ == null) {
          ensurePoisIsMutable();
          pois_.set(index, builderForValue.build());
          onChanged();
        } else {
          poisBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder addPois(innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf value) {
        if (poisBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoisIsMutable();
          pois_.add(value);
          onChanged();
        } else {
          poisBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder addPois(
          int index, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf value) {
        if (poisBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoisIsMutable();
          pois_.add(index, value);
          onChanged();
        } else {
          poisBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder addPois(
          innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder builderForValue) {
        if (poisBuilder_ == null) {
          ensurePoisIsMutable();
          pois_.add(builderForValue.build());
          onChanged();
        } else {
          poisBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder addPois(
          int index, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder builderForValue) {
        if (poisBuilder_ == null) {
          ensurePoisIsMutable();
          pois_.add(index, builderForValue.build());
          onChanged();
        } else {
          poisBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder addAllPois(
          java.lang.Iterable<? extends innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf> values) {
        if (poisBuilder_ == null) {
          ensurePoisIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pois_);
          onChanged();
        } else {
          poisBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder clearPois() {
        if (poisBuilder_ == null) {
          pois_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          poisBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public Builder removePois(int index) {
        if (poisBuilder_ == null) {
          ensurePoisIsMutable();
          pois_.remove(index);
          onChanged();
        } else {
          poisBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder getPoisBuilder(
          int index) {
        return getPoisFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder getPoisOrBuilder(
          int index) {
        if (poisBuilder_ == null) {
          return pois_.get(index);  } else {
          return poisBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public java.util.List<? extends innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder> 
           getPoisOrBuilderList() {
        if (poisBuilder_ != null) {
          return poisBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pois_);
        }
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder addPoisBuilder() {
        return getPoisFieldBuilder().addBuilder(
            innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.getDefaultInstance());
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder addPoisBuilder(
          int index) {
        return getPoisFieldBuilder().addBuilder(
            index, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.getDefaultInstance());
      }
      /**
       * <code>repeated .innerpeacer.mapdata.pbf.PoiPbf pois = 1;</code>
       */
      public java.util.List<innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder> 
           getPoisBuilderList() {
        return getPoisFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder> 
          getPoisFieldBuilder() {
        if (poisBuilder_ == null) {
          poisBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbf.Builder, innerpeacer.mapdata.pbf.TYPoiPbf.PoiPbfOrBuilder>(
                  pois_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pois_ = null;
        }
        return poisBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:innerpeacer.mapdata.pbf.PoiCollectionPbf)
    }

    // @@protoc_insertion_point(class_scope:innerpeacer.mapdata.pbf.PoiCollectionPbf)
    private static final innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf();
    }

    public static innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PoiCollectionPbf>
        PARSER = new com.google.protobuf.AbstractParser<PoiCollectionPbf>() {
      public PoiCollectionPbf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PoiCollectionPbf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PoiCollectionPbf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PoiCollectionPbf> getParserForType() {
      return PARSER;
    }

    public innerpeacer.mapdata.pbf.TYPoiPbf.PoiCollectionPbf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_innerpeacer_mapdata_pbf_PoiPbf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021t_y_poi_pbf.proto\022\027innerpeacer.mapdata" +
      ".pbf\"w\n\006PoiPbf\022\r\n\005poiID\030\002 \002(\t\022\r\n\005floor\030\005" +
      " \002(\005\022\r\n\005layer\030\007 \002(\005\022\014\n\004name\030\010 \001(\t\022\022\n\ncat" +
      "egoryID\030\t \001(\t\022\016\n\006labelX\030\013 \001(\001\022\016\n\006labelY\030" +
      "\014 \001(\001\"A\n\020PoiCollectionPbf\022-\n\004pois\030\001 \003(\0132" +
      "\037.innerpeacer.mapdata.pbf.PoiPbf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_innerpeacer_mapdata_pbf_PoiPbf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_innerpeacer_mapdata_pbf_PoiPbf_descriptor,
        new java.lang.String[] { "PoiID", "Floor", "Layer", "Name", "CategoryID", "LabelX", "LabelY", });
    internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_innerpeacer_mapdata_pbf_PoiCollectionPbf_descriptor,
        new java.lang.String[] { "Pois", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
