// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t_y_beacon_pbf.proto

package innerpeacer.beacon.pbf;

@SuppressWarnings({ "unused", "unchecked" })
public final class TYBeaconPbf {
	private TYBeaconPbf() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface TYLocatingBeaconPbfOrBuilder extends
			// @@protoc_insertion_point(interface_extends:innerpeacer.beacon.pbf.TYLocatingBeaconPbf)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 *	required string uuid = 1;
		 * </pre>
		 *
		 * <code>required uint32 major = 2;</code>
		 */
		boolean hasMajor();

		/**
		 * <pre>
		 *	required string uuid = 1;
		 * </pre>
		 *
		 * <code>required uint32 major = 2;</code>
		 */
		int getMajor();

		/**
		 * <code>required uint32 minor = 3;</code>
		 */
		boolean hasMinor();

		/**
		 * <code>required uint32 minor = 3;</code>
		 */
		int getMinor();

		/**
		 * <code>required double x = 4;</code>
		 */
		boolean hasX();

		/**
		 * <code>required double x = 4;</code>
		 */
		double getX();

		/**
		 * <code>required double y = 5;</code>
		 */
		boolean hasY();

		/**
		 * <code>required double y = 5;</code>
		 */
		double getY();

		/**
		 * <code>required double floor = 6;</code>
		 */
		boolean hasFloor();

		/**
		 * <code>required double floor = 6;</code>
		 */
		double getFloor();
	}

	/**
	 * Protobuf type {@code innerpeacer.beacon.pbf.TYLocatingBeaconPbf}
	 */
	public static final class TYLocatingBeaconPbf extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:innerpeacer.beacon.pbf.TYLocatingBeaconPbf)
			TYLocatingBeaconPbfOrBuilder {
		// Use TYLocatingBeaconPbf.newBuilder() to construct.
		private TYLocatingBeaconPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private TYLocatingBeaconPbf() {
			major_ = 0;
			minor_ = 0;
			x_ = 0D;
			y_ = 0D;
			floor_ = 0D;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private TYLocatingBeaconPbf(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 16: {
						bitField0_ |= 0x00000001;
						major_ = input.readUInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000002;
						minor_ = input.readUInt32();
						break;
					}
					case 33: {
						bitField0_ |= 0x00000004;
						x_ = input.readDouble();
						break;
					}
					case 41: {
						bitField0_ |= 0x00000008;
						y_ = input.readDouble();
						break;
					}
					case 49: {
						bitField0_ |= 0x00000010;
						floor_ = input.readDouble();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_fieldAccessorTable
					.ensureFieldAccessorsInitialized(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.class,
							innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder.class);
		}

		private int bitField0_;
		public static final int MAJOR_FIELD_NUMBER = 2;
		private int major_;

		/**
		 * <pre>
		 *	required string uuid = 1;
		 * </pre>
		 *
		 * <code>required uint32 major = 2;</code>
		 */
		public boolean hasMajor() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <pre>
		 *	required string uuid = 1;
		 * </pre>
		 *
		 * <code>required uint32 major = 2;</code>
		 */
		public int getMajor() {
			return major_;
		}

		public static final int MINOR_FIELD_NUMBER = 3;
		private int minor_;

		/**
		 * <code>required uint32 minor = 3;</code>
		 */
		public boolean hasMinor() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required uint32 minor = 3;</code>
		 */
		public int getMinor() {
			return minor_;
		}

		public static final int X_FIELD_NUMBER = 4;
		private double x_;

		/**
		 * <code>required double x = 4;</code>
		 */
		public boolean hasX() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>required double x = 4;</code>
		 */
		public double getX() {
			return x_;
		}

		public static final int Y_FIELD_NUMBER = 5;
		private double y_;

		/**
		 * <code>required double y = 5;</code>
		 */
		public boolean hasY() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>required double y = 5;</code>
		 */
		public double getY() {
			return y_;
		}

		public static final int FLOOR_FIELD_NUMBER = 6;
		private double floor_;

		/**
		 * <code>required double floor = 6;</code>
		 */
		public boolean hasFloor() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		/**
		 * <code>required double floor = 6;</code>
		 */
		public double getFloor() {
			return floor_;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasMajor()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMinor()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasX()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasY()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasFloor()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeUInt32(2, major_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeUInt32(3, minor_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeDouble(4, x_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeDouble(5, y_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeDouble(6, floor_);
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeUInt32Size(2, major_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeUInt32Size(3, minor_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, x_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(5, y_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeDoubleSize(6, floor_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf)) {
				return super.equals(obj);
			}
			innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf other = (innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf) obj;

			boolean result = true;
			result = result && (hasMajor() == other.hasMajor());
			if (hasMajor()) {
				result = result && (getMajor() == other.getMajor());
			}
			result = result && (hasMinor() == other.hasMinor());
			if (hasMinor()) {
				result = result && (getMinor() == other.getMinor());
			}
			result = result && (hasX() == other.hasX());
			if (hasX()) {
				result = result && (java.lang.Double.doubleToLongBits(getX()) == java.lang.Double
						.doubleToLongBits(other.getX()));
			}
			result = result && (hasY() == other.hasY());
			if (hasY()) {
				result = result && (java.lang.Double.doubleToLongBits(getY()) == java.lang.Double
						.doubleToLongBits(other.getY()));
			}
			result = result && (hasFloor() == other.hasFloor());
			if (hasFloor()) {
				result = result && (java.lang.Double.doubleToLongBits(getFloor()) == java.lang.Double
						.doubleToLongBits(other.getFloor()));
			}
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasMajor()) {
				hash = (37 * hash) + MAJOR_FIELD_NUMBER;
				hash = (53 * hash) + getMajor();
			}
			if (hasMinor()) {
				hash = (37 * hash) + MINOR_FIELD_NUMBER;
				hash = (53 * hash) + getMinor();
			}
			if (hasX()) {
				hash = (37 * hash) + X_FIELD_NUMBER;
				hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getX()));
			}
			if (hasY()) {
				hash = (37 * hash) + Y_FIELD_NUMBER;
				hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getY()));
			}
			if (hasFloor()) {
				hash = (37 * hash) + FLOOR_FIELD_NUMBER;
				hash = (53 * hash)
						+ com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getFloor()));
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code innerpeacer.beacon.pbf.TYLocatingBeaconPbf}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:innerpeacer.beacon.pbf.TYLocatingBeaconPbf)
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_fieldAccessorTable
						.ensureFieldAccessorsInitialized(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.class,
								innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder.class);
			}

			// Construct using
			// innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				major_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				minor_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				x_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000004);
				y_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000008);
				floor_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor;
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getDefaultInstanceForType() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.getDefaultInstance();
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf build() {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf buildPartial() {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf result = new innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.major_ = major_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.minor_ = minor_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.x_ = x_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.y_ = y_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.floor_ = floor_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf) {
					return mergeFrom((innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf other) {
				if (other == innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.getDefaultInstance())
					return this;
				if (other.hasMajor()) {
					setMajor(other.getMajor());
				}
				if (other.hasMinor()) {
					setMinor(other.getMinor());
				}
				if (other.hasX()) {
					setX(other.getX());
				}
				if (other.hasY()) {
					setY(other.getY());
				}
				if (other.hasFloor()) {
					setFloor(other.getFloor());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				if (!hasMajor()) {
					return false;
				}
				if (!hasMinor()) {
					return false;
				}
				if (!hasX()) {
					return false;
				}
				if (!hasY()) {
					return false;
				}
				if (!hasFloor()) {
					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int major_;

			/**
			 * <pre>
			 *	required string uuid = 1;
			 * </pre>
			 *
			 * <code>required uint32 major = 2;</code>
			 */
			public boolean hasMajor() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <pre>
			 *	required string uuid = 1;
			 * </pre>
			 *
			 * <code>required uint32 major = 2;</code>
			 */
			public int getMajor() {
				return major_;
			}

			/**
			 * <pre>
			 *	required string uuid = 1;
			 * </pre>
			 *
			 * <code>required uint32 major = 2;</code>
			 */
			public Builder setMajor(int value) {
				bitField0_ |= 0x00000001;
				major_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *	required string uuid = 1;
			 * </pre>
			 *
			 * <code>required uint32 major = 2;</code>
			 */
			public Builder clearMajor() {
				bitField0_ = (bitField0_ & ~0x00000001);
				major_ = 0;
				onChanged();
				return this;
			}

			private int minor_;

			/**
			 * <code>required uint32 minor = 3;</code>
			 */
			public boolean hasMinor() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required uint32 minor = 3;</code>
			 */
			public int getMinor() {
				return minor_;
			}

			/**
			 * <code>required uint32 minor = 3;</code>
			 */
			public Builder setMinor(int value) {
				bitField0_ |= 0x00000002;
				minor_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required uint32 minor = 3;</code>
			 */
			public Builder clearMinor() {
				bitField0_ = (bitField0_ & ~0x00000002);
				minor_ = 0;
				onChanged();
				return this;
			}

			private double x_;

			/**
			 * <code>required double x = 4;</code>
			 */
			public boolean hasX() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required double x = 4;</code>
			 */
			public double getX() {
				return x_;
			}

			/**
			 * <code>required double x = 4;</code>
			 */
			public Builder setX(double value) {
				bitField0_ |= 0x00000004;
				x_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required double x = 4;</code>
			 */
			public Builder clearX() {
				bitField0_ = (bitField0_ & ~0x00000004);
				x_ = 0D;
				onChanged();
				return this;
			}

			private double y_;

			/**
			 * <code>required double y = 5;</code>
			 */
			public boolean hasY() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>required double y = 5;</code>
			 */
			public double getY() {
				return y_;
			}

			/**
			 * <code>required double y = 5;</code>
			 */
			public Builder setY(double value) {
				bitField0_ |= 0x00000008;
				y_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required double y = 5;</code>
			 */
			public Builder clearY() {
				bitField0_ = (bitField0_ & ~0x00000008);
				y_ = 0D;
				onChanged();
				return this;
			}

			private double floor_;

			/**
			 * <code>required double floor = 6;</code>
			 */
			public boolean hasFloor() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			/**
			 * <code>required double floor = 6;</code>
			 */
			public double getFloor() {
				return floor_;
			}

			/**
			 * <code>required double floor = 6;</code>
			 */
			public Builder setFloor(double value) {
				bitField0_ |= 0x00000010;
				floor_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required double floor = 6;</code>
			 */
			public Builder clearFloor() {
				bitField0_ = (bitField0_ & ~0x00000010);
				floor_ = 0D;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:innerpeacer.beacon.pbf.TYLocatingBeaconPbf)
		}

		// @@protoc_insertion_point(class_scope:innerpeacer.beacon.pbf.TYLocatingBeaconPbf)
		private static final innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf();
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		@java.lang.Deprecated
		public static final com.google.protobuf.Parser<TYLocatingBeaconPbf> PARSER = new com.google.protobuf.AbstractParser<TYLocatingBeaconPbf>() {
			public TYLocatingBeaconPbf parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new TYLocatingBeaconPbf(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<TYLocatingBeaconPbf> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<TYLocatingBeaconPbf> getParserForType() {
			return PARSER;
		}

		public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface TYLocatingBeaconListPbfOrBuilder extends
			// @@protoc_insertion_point(interface_extends:innerpeacer.beacon.pbf.TYLocatingBeaconListPbf)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required string uuid = 1;</code>
		 */
		boolean hasUuid();

		/**
		 * <code>required string uuid = 1;</code>
		 */
		java.lang.String getUuid();

		/**
		 * <code>required string uuid = 1;</code>
		 */
		com.google.protobuf.ByteString getUuidBytes();

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> getBeaconsList();

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getBeacons(int index);

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		int getBeaconsCount();

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		java.util.List<? extends innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder> getBeaconsOrBuilderList();

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder getBeaconsOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code innerpeacer.beacon.pbf.TYLocatingBeaconListPbf}
	 */
	public static final class TYLocatingBeaconListPbf extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:innerpeacer.beacon.pbf.TYLocatingBeaconListPbf)
			TYLocatingBeaconListPbfOrBuilder {
		// Use TYLocatingBeaconListPbf.newBuilder() to construct.
		private TYLocatingBeaconListPbf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private TYLocatingBeaconListPbf() {
			uuid_ = "";
			beacons_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private TYLocatingBeaconListPbf(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000001;
						uuid_ = bs;
						break;
					}
					case 18: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							beacons_ = new java.util.ArrayList<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf>();
							mutable_bitField0_ |= 0x00000002;
						}
						beacons_.add(input.readMessage(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.PARSER,
								extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					beacons_ = java.util.Collections.unmodifiableList(beacons_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_fieldAccessorTable
					.ensureFieldAccessorsInitialized(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.class,
							innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.Builder.class);
		}

		private int bitField0_;
		public static final int UUID_FIELD_NUMBER = 1;
		private volatile java.lang.Object uuid_;

		/**
		 * <code>required string uuid = 1;</code>
		 */
		public boolean hasUuid() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string uuid = 1;</code>
		 */
		public java.lang.String getUuid() {
			java.lang.Object ref = uuid_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					uuid_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string uuid = 1;</code>
		 */
		public com.google.protobuf.ByteString getUuidBytes() {
			java.lang.Object ref = uuid_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				uuid_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int BEACONS_FIELD_NUMBER = 2;
		private java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> beacons_;

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		public java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> getBeaconsList() {
			return beacons_;
		}

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		public java.util.List<? extends innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder> getBeaconsOrBuilderList() {
			return beacons_;
		}

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		public int getBeaconsCount() {
			return beacons_.size();
		}

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getBeacons(int index) {
			return beacons_.get(index);
		}

		/**
		 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
		 */
		public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder getBeaconsOrBuilder(int index) {
			return beacons_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasUuid()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getBeaconsCount(); i++) {
				if (!getBeacons(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
			}
			for (int i = 0; i < beacons_.size(); i++) {
				output.writeMessage(2, beacons_.get(i));
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
			}
			for (int i = 0; i < beacons_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, beacons_.get(i));
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf)) {
				return super.equals(obj);
			}
			innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf other = (innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf) obj;

			boolean result = true;
			result = result && (hasUuid() == other.hasUuid());
			if (hasUuid()) {
				result = result && getUuid().equals(other.getUuid());
			}
			result = result && getBeaconsList().equals(other.getBeaconsList());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasUuid()) {
				hash = (37 * hash) + UUID_FIELD_NUMBER;
				hash = (53 * hash) + getUuid().hashCode();
			}
			if (getBeaconsCount() > 0) {
				hash = (37 * hash) + BEACONS_FIELD_NUMBER;
				hash = (53 * hash) + getBeaconsList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code innerpeacer.beacon.pbf.TYLocatingBeaconListPbf}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:innerpeacer.beacon.pbf.TYLocatingBeaconListPbf)
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbfOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.class,
								innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.Builder.class);
			}

			// Construct using
			// innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getBeaconsFieldBuilder();
				}
			}

			public Builder clear() {
				super.clear();
				uuid_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				if (beaconsBuilder_ == null) {
					beacons_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					beaconsBuilder_.clear();
				}
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor;
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf getDefaultInstanceForType() {
				return innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.getDefaultInstance();
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf build() {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf buildPartial() {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf result = new innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.uuid_ = uuid_;
				if (beaconsBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						beacons_ = java.util.Collections.unmodifiableList(beacons_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.beacons_ = beacons_;
				} else {
					result.beacons_ = beaconsBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf) {
					return mergeFrom((innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf other) {
				if (other == innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf.getDefaultInstance())
					return this;
				if (other.hasUuid()) {
					bitField0_ |= 0x00000001;
					uuid_ = other.uuid_;
					onChanged();
				}
				if (beaconsBuilder_ == null) {
					if (!other.beacons_.isEmpty()) {
						if (beacons_.isEmpty()) {
							beacons_ = other.beacons_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureBeaconsIsMutable();
							beacons_.addAll(other.beacons_);
						}
						onChanged();
					}
				} else {
					if (!other.beacons_.isEmpty()) {
						if (beaconsBuilder_.isEmpty()) {
							beaconsBuilder_.dispose();
							beaconsBuilder_ = null;
							beacons_ = other.beacons_;
							bitField0_ = (bitField0_ & ~0x00000002);
							beaconsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getBeaconsFieldBuilder() : null;
						} else {
							beaconsBuilder_.addAllMessages(other.beacons_);
						}
					}
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				if (!hasUuid()) {
					return false;
				}
				for (int i = 0; i < getBeaconsCount(); i++) {
					if (!getBeacons(i).isInitialized()) {
						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf) e
							.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object uuid_ = "";

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public boolean hasUuid() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public java.lang.String getUuid() {
				java.lang.Object ref = uuid_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						uuid_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public com.google.protobuf.ByteString getUuidBytes() {
				java.lang.Object ref = uuid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					uuid_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public Builder setUuid(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				uuid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public Builder clearUuid() {
				bitField0_ = (bitField0_ & ~0x00000001);
				uuid_ = getDefaultInstance().getUuid();
				onChanged();
				return this;
			}

			/**
			 * <code>required string uuid = 1;</code>
			 */
			public Builder setUuidBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				uuid_ = value;
				onChanged();
				return this;
			}

			private java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> beacons_ = java.util.Collections
					.emptyList();

			private void ensureBeaconsIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					beacons_ = new java.util.ArrayList<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf>(
							beacons_);
					bitField0_ |= 0x00000002;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder> beaconsBuilder_;

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> getBeaconsList() {
				if (beaconsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(beacons_);
				} else {
					return beaconsBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public int getBeaconsCount() {
				if (beaconsBuilder_ == null) {
					return beacons_.size();
				} else {
					return beaconsBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf getBeacons(int index) {
				if (beaconsBuilder_ == null) {
					return beacons_.get(index);
				} else {
					return beaconsBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder setBeacons(int index, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf value) {
				if (beaconsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureBeaconsIsMutable();
					beacons_.set(index, value);
					onChanged();
				} else {
					beaconsBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder setBeacons(int index,
					innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder builderForValue) {
				if (beaconsBuilder_ == null) {
					ensureBeaconsIsMutable();
					beacons_.set(index, builderForValue.build());
					onChanged();
				} else {
					beaconsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder addBeacons(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf value) {
				if (beaconsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureBeaconsIsMutable();
					beacons_.add(value);
					onChanged();
				} else {
					beaconsBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder addBeacons(int index, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf value) {
				if (beaconsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureBeaconsIsMutable();
					beacons_.add(index, value);
					onChanged();
				} else {
					beaconsBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder addBeacons(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder builderForValue) {
				if (beaconsBuilder_ == null) {
					ensureBeaconsIsMutable();
					beacons_.add(builderForValue.build());
					onChanged();
				} else {
					beaconsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder addBeacons(int index,
					innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder builderForValue) {
				if (beaconsBuilder_ == null) {
					ensureBeaconsIsMutable();
					beacons_.add(index, builderForValue.build());
					onChanged();
				} else {
					beaconsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder addAllBeacons(
					java.lang.Iterable<? extends innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf> values) {
				if (beaconsBuilder_ == null) {
					ensureBeaconsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, beacons_);
					onChanged();
				} else {
					beaconsBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder clearBeacons() {
				if (beaconsBuilder_ == null) {
					beacons_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					beaconsBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public Builder removeBeacons(int index) {
				if (beaconsBuilder_ == null) {
					ensureBeaconsIsMutable();
					beacons_.remove(index);
					onChanged();
				} else {
					beaconsBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder getBeaconsBuilder(int index) {
				return getBeaconsFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder getBeaconsOrBuilder(int index) {
				if (beaconsBuilder_ == null) {
					return beacons_.get(index);
				} else {
					return beaconsBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public java.util.List<? extends innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder> getBeaconsOrBuilderList() {
				if (beaconsBuilder_ != null) {
					return beaconsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(beacons_);
				}
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder addBeaconsBuilder() {
				return getBeaconsFieldBuilder()
						.addBuilder(innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.getDefaultInstance());
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder addBeaconsBuilder(int index) {
				return getBeaconsFieldBuilder().addBuilder(index,
						innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.getDefaultInstance());
			}

			/**
			 * <code>repeated .innerpeacer.beacon.pbf.TYLocatingBeaconPbf beacons = 2;</code>
			 */
			public java.util.List<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder> getBeaconsBuilderList() {
				return getBeaconsFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder> getBeaconsFieldBuilder() {
				if (beaconsBuilder_ == null) {
					beaconsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbf.Builder, innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconPbfOrBuilder>(
							beacons_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
					beacons_ = null;
				}
				return beaconsBuilder_;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:innerpeacer.beacon.pbf.TYLocatingBeaconListPbf)
		}

		// @@protoc_insertion_point(class_scope:innerpeacer.beacon.pbf.TYLocatingBeaconListPbf)
		private static final innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf();
		}

		public static innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		@java.lang.Deprecated
		public static final com.google.protobuf.Parser<TYLocatingBeaconListPbf> PARSER = new com.google.protobuf.AbstractParser<TYLocatingBeaconListPbf>() {
			public TYLocatingBeaconListPbf parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new TYLocatingBeaconListPbf(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<TYLocatingBeaconListPbf> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<TYLocatingBeaconListPbf> getParserForType() {
			return PARSER;
		}

		public innerpeacer.beacon.pbf.TYBeaconPbf.TYLocatingBeaconListPbf getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\024t_y_beacon_pbf.proto\022\026innerpeacer.beac"
				+ "on.pbf\"X\n\023TYLocatingBeaconPbf\022\r\n\005major\030\002"
				+ " \002(\r\022\r\n\005minor\030\003 \002(\r\022\t\n\001x\030\004 \002(\001\022\t\n\001y\030\005 \002("
				+ "\001\022\r\n\005floor\030\006 \002(\001\"e\n\027TYLocatingBeaconList"
				+ "Pbf\022\014\n\004uuid\030\001 \002(\t\022<\n\007beacons\030\002 \003(\0132+.inn"
				+ "erpeacer.beacon.pbf.TYLocatingBeaconPbf" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor = getDescriptor().getMessageTypes()
				.get(0);
		internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconPbf_descriptor,
				new java.lang.String[] { "Major", "Minor", "X", "Y", "Floor", });
		internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor = getDescriptor().getMessageTypes()
				.get(1);
		internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_innerpeacer_beacon_pbf_TYLocatingBeaconListPbf_descriptor,
				new java.lang.String[] { "Uuid", "Beacons", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
